version: '2'
services:
  proxy:
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    links:
      - web
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy

    volumes:
      - "./app:/data/app"
    logging:
      driver: "json-file"
      options:
        max-size: "10"
        max-file: "10"
    extra_hosts:
      - "gym:172.17.0.1"
      - "gym.shinecoding.co.uk:172.17.0.1"
      - "sync.shinecoding.co.uk:172.17.0.1"
